[general]
import = [ "/home/syafik/.config/alacritty/themes/catppuccin_mocha.toml" ]

[window]
padding = { x = 3, y = 3}
decorations = "Full"
startup_mode = "Maximized"

[font]
normal =      { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
bold =        { family = "JetBrainsMonoNL Nerd Font", style = "SemiBold" }
italic =      { family = "JetBrainsMonoNL Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNL Nerd Font", style = "SemiBold Italic" }
size = 10.5

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

[cursor]
style = { shape = "Beam", blinking = "On"}
